server.port: 8989
server.servlet.context-path: /bank-api

spring.security.user.name: bankapp
spring.security.user.password: changeit

# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
